<?php

namespace Database\Seeders;

use App\Models\Permission;
use App\Models\Organization;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $organizations = Organization::all();

        // Validate that organizations exist
        if ($organizations->isEmpty()) {
            throw new \Exception('No organizations found. Please run OrganizationSeeder first.');
        }

        // System permissions (global scope, no organization)
        $systemPermissions = [
            // User Management
            ['name' => 'View All Users', 'code' => 'users.view_all', 'display_name' => 'View All Users', 'description' => 'Can view all users in the system', 'resource' => 'users', 'action' => 'view_all', 'scope' => 'global', 'category' => 'User Management', 'group_name' => 'users', 'is_system_permission' => true, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 1],
            ['name' => 'Create Users', 'code' => 'users.create', 'display_name' => 'Create Users', 'description' => 'Can create new users', 'resource' => 'users', 'action' => 'create', 'scope' => 'global', 'category' => 'User Management', 'group_name' => 'users', 'is_system_permission' => true, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 2],
            ['name' => 'Update Users', 'code' => 'users.update', 'display_name' => 'Update Users', 'description' => 'Can update user information', 'resource' => 'users', 'action' => 'update', 'scope' => 'global', 'category' => 'User Management', 'group_name' => 'users', 'is_system_permission' => true, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 3],
            ['name' => 'Delete Users', 'code' => 'users.delete', 'display_name' => 'Delete Users', 'description' => 'Can delete users', 'resource' => 'users', 'action' => 'delete', 'scope' => 'global', 'category' => 'User Management', 'group_name' => 'users', 'is_system_permission' => true, 'is_dangerous' => true, 'requires_approval' => true, 'sort_order' => 4],
            ['name' => 'Manage User Roles', 'code' => 'users.manage_roles', 'display_name' => 'Manage User Roles', 'description' => 'Can assign and manage user roles', 'resource' => 'users', 'action' => 'manage', 'scope' => 'global', 'category' => 'User Management', 'group_name' => 'users', 'is_system_permission' => true, 'is_dangerous' => true, 'requires_approval' => true, 'sort_order' => 5],

            // Organization Management
            ['name' => 'View Organizations', 'code' => 'organizations.view', 'display_name' => 'View Organizations', 'description' => 'Can view organization information', 'resource' => 'organizations', 'action' => 'read', 'scope' => 'global', 'category' => 'Organization Management', 'group_name' => 'organizations', 'is_system_permission' => true, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 6],
            ['name' => 'Create Organizations', 'code' => 'organizations.create', 'display_name' => 'Create Organizations', 'description' => 'Can create new organizations', 'resource' => 'organizations', 'action' => 'create', 'scope' => 'global', 'category' => 'Organization Management', 'group_name' => 'organizations', 'is_system_permission' => true, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 7],
            ['name' => 'Update Organizations', 'code' => 'organizations.update', 'display_name' => 'Update Organizations', 'description' => 'Can update organization information', 'resource' => 'organizations', 'action' => 'update', 'scope' => 'global', 'category' => 'Organization Management', 'group_name' => 'organizations', 'is_system_permission' => true, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 8],
            ['name' => 'Delete Organizations', 'code' => 'organizations.delete', 'display_name' => 'Delete Organizations', 'description' => 'Can delete organizations', 'resource' => 'organizations', 'action' => 'delete', 'scope' => 'global', 'category' => 'Organization Management', 'group_name' => 'organizations', 'is_system_permission' => true, 'is_dangerous' => true, 'requires_approval' => true, 'sort_order' => 9],

            // Role Management
            ['name' => 'View Roles', 'code' => 'roles.view', 'display_name' => 'View Roles', 'description' => 'Can view role information', 'resource' => 'roles', 'action' => 'read', 'scope' => 'global', 'category' => 'Role Management', 'group_name' => 'roles', 'is_system_permission' => true, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 10],
            ['name' => 'Create Roles', 'code' => 'roles.create', 'display_name' => 'Create Roles', 'description' => 'Can create new roles', 'resource' => 'roles', 'action' => 'create', 'scope' => 'global', 'category' => 'Role Management', 'group_name' => 'roles', 'is_system_permission' => true, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 11],
            ['name' => 'Update Roles', 'code' => 'roles.update', 'display_name' => 'Update Roles', 'description' => 'Can update role information', 'resource' => 'roles', 'action' => 'update', 'scope' => 'global', 'category' => 'Role Management', 'group_name' => 'roles', 'is_system_permission' => true, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 12],
            ['name' => 'Delete Roles', 'code' => 'roles.delete', 'display_name' => 'Delete Roles', 'description' => 'Can delete roles', 'resource' => 'roles', 'action' => 'delete', 'scope' => 'global', 'category' => 'Role Management', 'group_name' => 'roles', 'is_system_permission' => true, 'is_dangerous' => true, 'requires_approval' => true, 'sort_order' => 13],
            ['name' => 'Manage Role Permissions', 'code' => 'roles.manage_permissions', 'display_name' => 'Manage Role Permissions', 'description' => 'Can assign permissions to roles', 'resource' => 'roles', 'action' => 'manage', 'scope' => 'global', 'category' => 'Role Management', 'group_name' => 'roles', 'is_system_permission' => true, 'is_dangerous' => true, 'requires_approval' => true, 'sort_order' => 14],

            // Permission Management
            ['name' => 'View Permissions', 'code' => 'permissions.view', 'display_name' => 'View Permissions', 'description' => 'Can view permission information', 'resource' => 'permissions', 'action' => 'read', 'scope' => 'global', 'category' => 'Permission Management', 'group_name' => 'permissions', 'is_system_permission' => true, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 15],
            ['name' => 'Create Permissions', 'code' => 'permissions.create', 'display_name' => 'Create Permissions', 'description' => 'Can create new permissions', 'resource' => 'permissions', 'action' => 'create', 'scope' => 'global', 'category' => 'Permission Management', 'group_name' => 'permissions', 'is_system_permission' => true, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 16],
            ['name' => 'Update Permissions', 'code' => 'permissions.update', 'display_name' => 'Update Permissions', 'description' => 'Can update permission information', 'resource' => 'permissions', 'action' => 'update', 'scope' => 'global', 'category' => 'Permission Management', 'group_name' => 'permissions', 'is_system_permission' => true, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 17],
            ['name' => 'Delete Permissions', 'code' => 'permissions.delete', 'display_name' => 'Delete Permissions', 'description' => 'Can delete permissions', 'resource' => 'permissions', 'action' => 'delete', 'scope' => 'global', 'category' => 'Permission Management', 'group_name' => 'permissions', 'is_system_permission' => true, 'is_dangerous' => true, 'requires_approval' => true, 'sort_order' => 18],

            // System Management
            ['name' => 'View System Logs', 'code' => 'system_logs.view', 'display_name' => 'View System Logs', 'description' => 'Can view system logs', 'resource' => 'system_logs', 'action' => 'read', 'scope' => 'global', 'category' => 'System Management', 'group_name' => 'system', 'is_system_permission' => true, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 19],
            ['name' => 'Manage System Settings', 'code' => 'system.manage', 'display_name' => 'Manage System Settings', 'description' => 'Can manage system-wide settings', 'resource' => 'system_logs', 'action' => 'manage', 'scope' => 'global', 'category' => 'System Management', 'group_name' => 'system', 'is_system_permission' => true, 'is_dangerous' => true, 'requires_approval' => true, 'sort_order' => 20],
        ];

        // Create system permissions (no organization)
        foreach ($systemPermissions as $permission) {
            Permission::updateOrCreate(
                ['code' => $permission['code']], // Search by code
                $permission // Update or create with all data
            );
        }

        // Organization-specific permissions
        foreach ($organizations as $organization) {
            $orgPermissions = [
                // User Management (Organization Scope)
                ['name' => 'View Organization Users', 'code' => 'users.view_org', 'display_name' => 'View Organization Users', 'description' => 'Can view users in the organization', 'resource' => 'users', 'action' => 'view_own', 'scope' => 'organization', 'category' => 'User Management', 'group_name' => 'users', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 21],
                ['name' => 'Create Organization Users', 'code' => 'users.create_org', 'display_name' => 'Create Organization Users', 'description' => 'Can create users in the organization', 'resource' => 'users', 'action' => 'create', 'scope' => 'organization', 'category' => 'User Management', 'group_name' => 'users', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 22],
                ['name' => 'Update Organization Users', 'code' => 'users.update_org', 'display_name' => 'Update Organization Users', 'description' => 'Can update users in the organization', 'resource' => 'users', 'action' => 'update', 'scope' => 'organization', 'category' => 'User Management', 'group_name' => 'users', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 23],
                ['name' => 'Delete Organization Users', 'code' => 'users.delete_org', 'display_name' => 'Delete Organization Users', 'description' => 'Can delete users in the organization', 'resource' => 'users', 'action' => 'delete', 'scope' => 'organization', 'category' => 'User Management', 'group_name' => 'users', 'is_system_permission' => false, 'is_dangerous' => true, 'requires_approval' => true, 'sort_order' => 24],

                // Agent Management
                ['name' => 'View Agents', 'code' => 'agents.view', 'display_name' => 'View Agents', 'description' => 'Can view chatbot agents', 'resource' => 'agents', 'action' => 'read', 'scope' => 'organization', 'category' => 'Agent Management', 'group_name' => 'agents', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 25],
                ['name' => 'Create Agents', 'code' => 'agents.create', 'display_name' => 'Create Agents', 'description' => 'Can create new chatbot agents', 'resource' => 'agents', 'action' => 'create', 'scope' => 'organization', 'category' => 'Agent Management', 'group_name' => 'agents', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 26],
                ['name' => 'Update Agents', 'code' => 'agents.update', 'display_name' => 'Update Agents', 'description' => 'Can update chatbot agents', 'resource' => 'agents', 'action' => 'update', 'scope' => 'organization', 'category' => 'Agent Management', 'group_name' => 'agents', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 27],
                ['name' => 'Delete Agents', 'code' => 'agents.delete', 'display_name' => 'Delete Agents', 'description' => 'Can delete chatbot agents', 'resource' => 'agents', 'action' => 'delete', 'scope' => 'organization', 'category' => 'Agent Management', 'group_name' => 'agents', 'is_system_permission' => false, 'is_dangerous' => true, 'requires_approval' => true, 'sort_order' => 28],
                ['name' => 'Execute Agents', 'code' => 'agents.execute', 'display_name' => 'Execute Agents', 'description' => 'Can execute and test chatbot agents', 'resource' => 'agents', 'action' => 'execute', 'scope' => 'organization', 'category' => 'Agent Management', 'group_name' => 'agents', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 29],

                // Customer Management
                ['name' => 'View Customers', 'code' => 'customers.view', 'display_name' => 'View Customers', 'description' => 'Can view customer information', 'resource' => 'customers', 'action' => 'read', 'scope' => 'organization', 'category' => 'Customer Management', 'group_name' => 'customers', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 30],
                ['name' => 'Create Customers', 'code' => 'customers.create', 'display_name' => 'Create Customers', 'description' => 'Can create new customers', 'resource' => 'customers', 'action' => 'create', 'scope' => 'organization', 'category' => 'Customer Management', 'group_name' => 'customers', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 31],
                ['name' => 'Update Customers', 'code' => 'customers.update', 'display_name' => 'Update Customers', 'description' => 'Can update customer information', 'resource' => 'customers', 'action' => 'update', 'scope' => 'organization', 'category' => 'Customer Management', 'group_name' => 'customers', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 32],
                ['name' => 'Delete Customers', 'code' => 'customers.delete', 'display_name' => 'Delete Customers', 'description' => 'Can delete customers', 'resource' => 'customers', 'action' => 'delete', 'scope' => 'organization', 'category' => 'Customer Management', 'group_name' => 'customers', 'is_system_permission' => false, 'is_dangerous' => true, 'requires_approval' => true, 'sort_order' => 33],

                // Chat Session Management
                ['name' => 'View Chat Sessions', 'code' => 'chat_sessions.view', 'display_name' => 'View Chat Sessions', 'description' => 'Can view chat sessions', 'resource' => 'chat_sessions', 'action' => 'read', 'scope' => 'organization', 'category' => 'Chat Management', 'group_name' => 'chat', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 34],
                ['name' => 'Create Chat Sessions', 'code' => 'chat_sessions.create', 'display_name' => 'Create Chat Sessions', 'description' => 'Can create new chat sessions', 'resource' => 'chat_sessions', 'action' => 'create', 'scope' => 'organization', 'category' => 'Chat Management', 'group_name' => 'chat', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 35],
                ['name' => 'Update Chat Sessions', 'code' => 'chat_sessions.update', 'display_name' => 'Update Chat Sessions', 'description' => 'Can update chat sessions', 'resource' => 'chat_sessions', 'action' => 'update', 'scope' => 'organization', 'category' => 'Chat Management', 'group_name' => 'chat', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 36],
                ['name' => 'Delete Chat Sessions', 'code' => 'chat_sessions.delete', 'display_name' => 'Delete Chat Sessions', 'description' => 'Can delete chat sessions', 'resource' => 'chat_sessions', 'action' => 'delete', 'scope' => 'organization', 'category' => 'Chat Management', 'group_name' => 'chat', 'is_system_permission' => false, 'is_dangerous' => true, 'requires_approval' => true, 'sort_order' => 37],

                // Message Management
                ['name' => 'View Messages', 'code' => 'messages.view', 'display_name' => 'View Messages', 'description' => 'Can view messages', 'resource' => 'messages', 'action' => 'read', 'scope' => 'organization', 'category' => 'Message Management', 'group_name' => 'messages', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 38],
                ['name' => 'Create Messages', 'code' => 'messages.create', 'display_name' => 'Create Messages', 'description' => 'Can create new messages', 'resource' => 'messages', 'action' => 'create', 'scope' => 'organization', 'category' => 'Message Management', 'group_name' => 'messages', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 39],
                ['name' => 'Update Messages', 'code' => 'messages.update', 'display_name' => 'Update Messages', 'description' => 'Can update messages', 'resource' => 'messages', 'action' => 'update', 'scope' => 'organization', 'category' => 'Message Management', 'group_name' => 'messages', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 40],
                ['name' => 'Delete Messages', 'code' => 'messages.delete', 'display_name' => 'Delete Messages', 'description' => 'Can delete messages', 'resource' => 'messages', 'action' => 'delete', 'scope' => 'organization', 'category' => 'Message Management', 'group_name' => 'messages', 'is_system_permission' => false, 'is_dangerous' => true, 'requires_approval' => true, 'sort_order' => 41],

                // Knowledge Base Management
                ['name' => 'View Knowledge Articles', 'code' => 'knowledge_articles.view', 'display_name' => 'View Knowledge Articles', 'description' => 'Can view knowledge base articles', 'resource' => 'knowledge_articles', 'action' => 'read', 'scope' => 'organization', 'category' => 'Knowledge Management', 'group_name' => 'knowledge', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 42],
                ['name' => 'Create Knowledge Articles', 'code' => 'knowledge_articles.create', 'display_name' => 'Create Knowledge Articles', 'description' => 'Can create new knowledge base articles', 'resource' => 'knowledge_articles', 'action' => 'create', 'scope' => 'organization', 'category' => 'Knowledge Management', 'group_name' => 'knowledge', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 43],
                ['name' => 'Update Knowledge Articles', 'code' => 'knowledge_articles.update', 'display_name' => 'Update Knowledge Articles', 'description' => 'Can update knowledge base articles', 'resource' => 'knowledge_articles', 'action' => 'update', 'scope' => 'organization', 'category' => 'Knowledge Management', 'group_name' => 'knowledge', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 44],
                ['name' => 'Delete Knowledge Articles', 'code' => 'knowledge_articles.delete', 'display_name' => 'Delete Knowledge Articles', 'description' => 'Can delete knowledge base articles', 'resource' => 'knowledge_articles', 'action' => 'delete', 'scope' => 'organization', 'category' => 'Knowledge Management', 'group_name' => 'knowledge', 'is_system_permission' => false, 'is_dangerous' => true, 'requires_approval' => true, 'sort_order' => 45],
                ['name' => 'Publish Knowledge Articles', 'code' => 'knowledge_articles.publish', 'display_name' => 'Publish Knowledge Articles', 'description' => 'Can publish knowledge base articles', 'resource' => 'knowledge_articles', 'action' => 'publish', 'scope' => 'organization', 'category' => 'Knowledge Management', 'group_name' => 'knowledge', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 46],

                // Bot Personality Management
                ['name' => 'View Bot Personalities', 'code' => 'bot_personalities.view', 'display_name' => 'View Bot Personalities', 'description' => 'Can view bot personalities', 'resource' => 'bot_personalities', 'action' => 'read', 'scope' => 'organization', 'category' => 'Bot Management', 'group_name' => 'bot', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 47],
                ['name' => 'Create Bot Personalities', 'code' => 'bot_personalities.create', 'display_name' => 'Create Bot Personalities', 'description' => 'Can create new bot personalities', 'resource' => 'bot_personalities', 'action' => 'create', 'scope' => 'organization', 'category' => 'Bot Management', 'group_name' => 'bot', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 48],
                ['name' => 'Update Bot Personalities', 'code' => 'bot_personalities.update', 'display_name' => 'Update Bot Personalities', 'description' => 'Can update bot personalities', 'resource' => 'bot_personalities', 'action' => 'update', 'scope' => 'organization', 'category' => 'Bot Management', 'group_name' => 'bot', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 49],
                ['name' => 'Delete Bot Personalities', 'code' => 'bot_personalities.delete', 'display_name' => 'Delete Bot Personalities', 'description' => 'Can delete bot personalities', 'resource' => 'bot_personalities', 'action' => 'delete', 'scope' => 'organization', 'category' => 'Bot Management', 'group_name' => 'bot', 'is_system_permission' => false, 'is_dangerous' => true, 'requires_approval' => true, 'sort_order' => 50],

                // Channel Configuration Management
                ['name' => 'View Channel Configs', 'code' => 'channel_configs.view', 'display_name' => 'View Channel Configs', 'description' => 'Can view channel configurations', 'resource' => 'channel_configs', 'action' => 'read', 'scope' => 'organization', 'category' => 'Channel Management', 'group_name' => 'channels', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 51],
                ['name' => 'Create Channel Configs', 'code' => 'channel_configs.create', 'display_name' => 'Create Channel Configs', 'description' => 'Can create new channel configurations', 'resource' => 'channel_configs', 'action' => 'create', 'scope' => 'organization', 'category' => 'Channel Management', 'group_name' => 'channels', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 52],
                ['name' => 'Update Channel Configs', 'code' => 'channel_configs.update', 'display_name' => 'Update Channel Configs', 'description' => 'Can update channel configurations', 'resource' => 'channel_configs', 'action' => 'update', 'scope' => 'organization', 'category' => 'Channel Management', 'group_name' => 'channels', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 53],
                ['name' => 'Delete Channel Configs', 'code' => 'channel_configs.delete', 'display_name' => 'Delete Channel Configs', 'description' => 'Can delete channel configurations', 'resource' => 'channel_configs', 'action' => 'delete', 'scope' => 'organization', 'category' => 'Channel Management', 'group_name' => 'channels', 'is_system_permission' => false, 'is_dangerous' => true, 'requires_approval' => true, 'sort_order' => 54],

                // Analytics Management
                ['name' => 'View Analytics', 'code' => 'analytics.view', 'display_name' => 'View Analytics', 'description' => 'Can view analytics and reports', 'resource' => 'analytics', 'action' => 'read', 'scope' => 'organization', 'category' => 'Analytics', 'group_name' => 'analytics', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 55],
                ['name' => 'Export Analytics', 'code' => 'analytics.export', 'display_name' => 'Export Analytics', 'description' => 'Can export analytics data', 'resource' => 'analytics', 'action' => 'export', 'scope' => 'organization', 'category' => 'Analytics', 'group_name' => 'analytics', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 56],

                // Billing Management
                ['name' => 'View Billing', 'code' => 'billing.view', 'display_name' => 'View Billing', 'description' => 'Can view billing information', 'resource' => 'billing', 'action' => 'read', 'scope' => 'organization', 'category' => 'Billing', 'group_name' => 'billing', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 57],
                ['name' => 'Manage Billing', 'code' => 'billing.manage', 'display_name' => 'Manage Billing', 'description' => 'Can manage billing and subscriptions', 'resource' => 'billing', 'action' => 'manage', 'scope' => 'organization', 'category' => 'Billing', 'group_name' => 'billing', 'is_system_permission' => false, 'is_dangerous' => true, 'requires_approval' => true, 'sort_order' => 58],

                // API Management
                ['name' => 'View API Keys', 'code' => 'api_keys.view', 'display_name' => 'View API Keys', 'description' => 'Can view API keys', 'resource' => 'api_keys', 'action' => 'read', 'scope' => 'organization', 'category' => 'API Management', 'group_name' => 'api', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 59],
                ['name' => 'Create API Keys', 'code' => 'api_keys.create', 'display_name' => 'Create API Keys', 'description' => 'Can create new API keys', 'resource' => 'api_keys', 'action' => 'create', 'scope' => 'organization', 'category' => 'API Management', 'group_name' => 'api', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 60],
                ['name' => 'Update API Keys', 'code' => 'api_keys.update', 'display_name' => 'Update API Keys', 'description' => 'Can update API keys', 'resource' => 'api_keys', 'action' => 'update', 'scope' => 'organization', 'category' => 'API Management', 'group_name' => 'api', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 61],
                ['name' => 'Delete API Keys', 'code' => 'api_keys.delete', 'display_name' => 'Delete API Keys', 'description' => 'Can delete API keys', 'resource' => 'api_keys', 'action' => 'delete', 'scope' => 'organization', 'category' => 'API Management', 'group_name' => 'api', 'is_system_permission' => false, 'is_dangerous' => true, 'requires_approval' => true, 'sort_order' => 62],

                // Webhook Management
                ['name' => 'View Webhooks', 'code' => 'webhooks.view', 'display_name' => 'View Webhooks', 'description' => 'Can view webhooks', 'resource' => 'webhooks', 'action' => 'read', 'scope' => 'organization', 'category' => 'Webhook Management', 'group_name' => 'webhooks', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 63],
                ['name' => 'Create Webhooks', 'code' => 'webhooks.create', 'display_name' => 'Create Webhooks', 'description' => 'Can create new webhooks', 'resource' => 'webhooks', 'action' => 'create', 'scope' => 'organization', 'category' => 'Webhook Management', 'group_name' => 'webhooks', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 64],
                ['name' => 'Update Webhooks', 'code' => 'webhooks.update', 'display_name' => 'Update Webhooks', 'description' => 'Can update webhooks', 'resource' => 'webhooks', 'action' => 'update', 'scope' => 'organization', 'category' => 'Webhook Management', 'group_name' => 'webhooks', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 65],
                ['name' => 'Delete Webhooks', 'code' => 'webhooks.delete', 'display_name' => 'Delete Webhooks', 'description' => 'Can delete webhooks', 'resource' => 'webhooks', 'action' => 'delete', 'scope' => 'organization', 'category' => 'Webhook Management', 'group_name' => 'webhooks', 'is_system_permission' => false, 'is_dangerous' => true, 'requires_approval' => true, 'sort_order' => 66],

                // Workflow Management
                ['name' => 'View Workflows', 'code' => 'workflows.view', 'display_name' => 'View Workflows', 'description' => 'Can view workflows', 'resource' => 'workflows', 'action' => 'read', 'scope' => 'organization', 'category' => 'Workflow Management', 'group_name' => 'workflows', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 67],
                ['name' => 'Create Workflows', 'code' => 'workflows.create', 'display_name' => 'Create Workflows', 'description' => 'Can create new workflows', 'resource' => 'workflows', 'action' => 'create', 'scope' => 'organization', 'category' => 'Workflow Management', 'group_name' => 'workflows', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 68],
                ['name' => 'Update Workflows', 'code' => 'workflows.update', 'display_name' => 'Update Workflows', 'description' => 'Can update workflows', 'resource' => 'workflows', 'action' => 'update', 'scope' => 'organization', 'category' => 'Workflow Management', 'group_name' => 'workflows', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 69],
                ['name' => 'Delete Workflows', 'code' => 'workflows.delete', 'display_name' => 'Delete Workflows', 'description' => 'Can delete workflows', 'resource' => 'workflows', 'action' => 'delete', 'scope' => 'organization', 'category' => 'Workflow Management', 'group_name' => 'workflows', 'is_system_permission' => false, 'is_dangerous' => true, 'requires_approval' => true, 'sort_order' => 70],
                ['name' => 'Execute Workflows', 'code' => 'workflows.execute', 'display_name' => 'Execute Workflows', 'description' => 'Can execute workflows', 'resource' => 'workflows', 'action' => 'execute', 'scope' => 'organization', 'category' => 'Workflow Management', 'group_name' => 'workflows', 'is_system_permission' => false, 'is_dangerous' => false, 'requires_approval' => false, 'sort_order' => 71],
            ];

            foreach ($orgPermissions as $permission) {
                $permission['organization_id'] = $organization->id;
                Permission::updateOrCreate(
                    ['organization_id' => $organization->id, 'code' => $permission['code']], // Search by organization_id and code
                    $permission // Update or create with all data
                );
            }
        }
    }
}
