version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:9000/api}
        VITE_NODE_ENV: ${VITE_NODE_ENV:-production}
    container_name: chatbot-frontend
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    restart: unless-stopped
